### ISSUE TITLE
Problem with running application

### ISSUE THREAD

**Issue by Pelcomp** [Shopify/example-ruby-app#5]
Hi
I created application with "Building a public Shopify application" tutorial and this repo.
App works properly locally with ngrok and on server when I start it in SSH console with "ruby app.rb" or "ruby app.rb &".

But when I close console or put another command, application stop working.
I can get it from App store but after clicking "Install app" I have an error:

- when I put another command to console:

```
ActiveResource::UnauthorizedAccess at /giftbasket/auth Failed. 
Response code = 401. Response message = Unauthorized.
app.rb in create_order_webhook
unless ShopifyAPI::Webhook.find(:all).any?
sinatra.error:#<ActiveResource::UnauthorizedAccess: Failed. Response code = 401. Response message = Unauthorized.>
sinatra.route: GET /giftbasket/auth
```

- when I close console:

```
Errno::EIO at /giftbasket/auth
Input/output error @ io_write - <STDERR>
.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb in service
si.service(req, res)
sinatra.error:#<ActiveResource::UnauthorizedAccess: Failed. Response code = 401. Response message = Unauthorized.>
sinatra.route: GET /giftbasket/auth
```
 Please help me run the application to work all time.

**Comment by jamiemtdwyer** [comment]
Hey Pelcomp,

This is a known limitation of this naive example application – when the application dies, all of the tokens stored in local memory will be discarded. A token is needed to authenticate with the shop, hence the 401 error.

In order to have this continue working, you would need to build some logic into the app to redirect back to the `auth` route when authentication fails. However, this will cause issues with processing webhook data. You may want to look into https://github.com/janko-m/sinatra-activerecord or another method of more permanent token storage.
